
inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_url
    - find_by_commit
    - find_by_service_and_repo
    - find_by_nickname
